amcl:
  ros__parameters:
    use_sim_time: True  # 시뮬레이션 시간을 사용할지 여부
    alpha1: 0.2  # 로봇의 회전 오차 관련 매개변수
    alpha2: 0.2  # 로봇의 이동 오차 관련 매개변수
    alpha3: 0.2  # 로봇의 이동 시 회전 오차 매개변수
    alpha4: 0.2  # 로봇의 회전 시 이동 오차 매개변수
    alpha5: 0.2  # 추가적인 오차 매개변수
    base_frame_id: "base_link"  # 로봇의 기본 프레임 ID
    beam_skip_distance: 0.5  # 레이저 빔 스킵 거리
    beam_skip_error_threshold: 0.9  # 빔 스킵 허용 오차 임계값
    beam_skip_threshold: 0.3  # 빔 스킵 임계값
    do_beamskip: false  # 빔 스킵 사용 여부
    global_frame_id: "map"  # 글로벌 맵 프레임 ID
    lambda_short: 0.1  # 짧은 거리 레이저 스캔에 대한 가중치
    laser_likelihood_max_dist: 2.0  # 레이저 측정치 최대 허용 거리
    laser_max_range: 100.0  # 레이저 최대 측정 범위
    laser_min_range: -1.0  # 레이저 최소 측정 범위
    laser_model_type: "likelihood_field"  # 레이저 모델 방식
    max_beams: 60  # 사용할 레이저 빔 최대 개수
    max_particles: 2000  # 입자 필터의 최대 입자 수
    # min_particles: 500  # 입자 필터의 최소 입자 수
    min_particles: 800  # 수정 **입자 필터의 최소 입자 수
    odom_frame_id: "odom"  # 오도메트리 프레임 ID
    pf_err: 0.05  # 입자 필터의 오차 확률
    pf_z: 0.99  # 입자 필터의 신뢰도
    recovery_alpha_fast: 0.0  # 빠른 복구 매개변수
    recovery_alpha_slow: 0.0  # 느린 복구 매개변수
    resample_interval: 1  # 입자 재샘플링 간격
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # 로봇 이동 모델 유형
    save_pose_rate: 0.5  # 로봇 위치 저장 빈도
    sigma_hit: 0.2  # 레이저 측정 노이즈의 표준편차
    tf_broadcast: true  # tf 변환 정보 브로드캐스팅 여부
    # transform_tolerance: 1.0  # tf 변환 허용 시간 (초)
    transform_tolerance: 1.0  #  수정 **tf 변환 허용 시간 (초)
    #update_min_a: 0.2  # 최소 회전 각도 업데이트 기준
    #update_min_d: 0.25  # 최소 이동 거리 업데이트 기준

    update_min_a: 0.1  # 수정 ** 최소 회전 각도 업데이트 기준
    update_min_d: 0.15  # 수정 ** 최소 이동 거리 업데이트 기준
    z_hit: 0.5  # 센서가 실제 장애물을 정확히 탐지한 확률 가중치
    z_max: 0.05  # 센서 최대 거리 확률 가중치
    z_rand: 0.5  # 랜덤 측정 확률 가중치
    z_short: 0.05  # 실제 거리보다 짧게 측정될 확률 가중치
    scan_topic: scan  # 사용할 레이저 스캔 토픽

map_server:
  ros__parameters:
    use_sim_time: True  # 시뮬레이션 시간 사용 여부
    yaml_filename: ""  # 지도 YAML 파일 경로 (런치 파일에서 별도 설정)

map_saver:
  ros__parameters:
    use_sim_time: True  # 시뮬레이션 시간 사용 여부
    save_map_timeout: 5.0  # 지도 저장 대기 최대 시간 (초)
    free_thresh_default: 0.25  # 자유공간 임계값
    occupied_thresh_default: 0.65  # 점유공간 임계값
    map_subscribe_transient_local: True  # 일시적 로컬 지도 구독 여부
